### ISSUE TITLE
Updated to latest version 2.1.1, getting error

### ISSUE THREAD

**Issue by Abdullah-J01** [robmarshall/next-gravity-forms#67] opened 2024-08-05 15:26 UTC
<img width="1424" alt="image" src="https://github.com/user-attachments/assets/80c5cf82-da7a-470d-be2f-0975b84b1f5c">

Having this issue after updating to latest version
Previously, i was using 0.1.40, but suddenly it stopped working as it started giving random IDs to the fields
For example: i have an input with an ID:input_18_71
It started giving: input_<someLongRandomCharacters>
I updated the package version hoping it would fix it, but now i am having this error shown in the image
Any ideas?

**Comment by Abdullah-J01** [comment] 2024-08-05 20:52
@robmarshall  - any idea what could be the issue? `const form = await getGravityForm(18);` this part is working fine, i console logged the output and seems to be returning correct data. However, still having this "replace" error

Could this be due to having "Pages" in the gravity form? But i had that before as well

**Comment by Gytjarek** [comment] 2024-08-06 06:51
@Abdullah-J01 most likely, it's related to the Captcha field. Can you confirm if you have it in your form? Could you export your form so I can try to reproduce it?

**Comment by Socipedia** [comment] 2024-08-06 10:08
@Gytjarek this my json form 
[gravityforms-export-2024-08-06.json](https://github.com/user-attachments/files/16508795/gravityforms-export-2024-08-06.json)

**Comment by Abdullah-J01** [comment] 2024-08-06 10:36
[gravityforms-export-2024-08-06.json](https://github.com/user-attachments/files/16509049/gravityforms-export-2024-08-06.json)
@Gytjarek  - Here is the exported form. It is a big form, but it worked fine with version 0.1.40, but suddenly, that version started giving random IDs to input fields and I was using those IDs to manually create pages in frontend, that's why i could no longer use the forms properly.
Now after updating to latest version, i am having error which i shared earlier

**Comment by Gytjarek** [comment] 2024-08-06 14:46
@Abdullah-J01 I just released the new 2.1.2 version with a fix for you. It would be great if you could collaborate on the project in the future. If you find any errors or improvements, you are very welcome to create a PR. I have a main job and work on this in my free time, so I can't handle everything

**Comment by Abdullah-J01** [comment] 2024-08-07 16:57
@Gytjarek - Thank you!
The issue has now been fixed
Surely I would love to contribute as this project has been very useful for me.
There are still some issues that we can work on, like presetValues is currently not working for me like it did in old version etc.

**Comment by Gytjarek** [comment] 2024-08-07 17:46
@Abdullah-J01 Could you elaborate on it? What exactly isn't working? Please provide as much detail as possible

**Comment by Abdullah-J01** [comment] 2024-08-07 17:52
@Gytjarek  - basically the presetValues

<GravityFormForm
          data={form}
          presetValues={{
            input_71: zipCode,
            input_180: leadID,
            input_178: trustedFormCertUrl,
            input_179: trustedFormPingUrl,
            input_189: affiliateLender,
          }}
          navigate={successHandler}
        />
        
        input_71 should get the vlaue of zipCode, but it stays empty, previously it would populate

**Comment by Gytjarek** [comment] 2024-08-08 09:06
@Abdullah-J01 Check the Readme about `navigate` and `successCallback`. I hope it will make it clear. 
About `presetValues`, the functionality has been changed to support the parameter name input https://docs.gravityforms.com/using-dynamic-population/#h-getting-started, since we can't read query params directly within the package, it should be passed through that prop. However, I will also make it possible to support `input_ID` as it was previously (it was lost somewhere durnig development)

**Comment by Gytjarek** [comment] 2024-09-05 14:07
@Abdullah-J01 all issues should be resolved in v2.1.3, I'm closing it now

**Closed by Gytjarek** 2024-09-05 14:07 UTC
